apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-dsc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode : efs-ap
  fileSystemId : "{{ .Values.efs_id }}"
  directoryPerms : "775"
reclaimPolicy: Retain